### ISSUE TITLE
Keep getting a Proxy task failed:ConnectionRefusedError and then the program crashes

### ISSUE THREAD

**Issue by rszimm** [snicker/juicepassproxy#83]
I keep getting this error in the log:
`ERROR     [__main__] A JuicePass Proxy task failed: ConnectionRefusedError: [Errno 111] Connection refused`

Here's what's in my juicepassproxy.yaml
```
ENELX_IP: 158.47.1.128
ENELX_PORT: '8051'
ENELX_SERVER: juicenet-udp-prod4-usa.enelx.com
JUICEBOX_ID: <redacted>
LOCAL_IP: 172.16.100.2
```
Here's what I get when I telnet into my juicebox before I run juiceboxproxy:

```
Trying 192.168.10.18...
Connected to juicebox1.lan.
Escape character is .
EMWERK-JB201-1.0.46, Gecko_OS-STANDARD-4.2.7-11064, WGM160P
> list
list
! # Type  Info
# 1 FILE  godaddy_ca.pem-1.0.0 (1390, 0)
# 2 UDPC  juicenet-udp-prod4-usa.enelx.com:8051 (6070)
> exit
```

Eventually the whole thing craps out (you can see the unhandled exception in the log)

[juicepassproxy.log](https://github.com/user-attachments/files/16697429/juicepassproxy.log)

**Comment by rszimm** [comment]
Oh, one other thing.  Here's my docker-compose file:
```
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
services:
  juicepassproxy:
    image: ghcr.io/snicker/juicepassproxy:latest
    hostname: juicepassproxy
    container_name: juicepassproxy
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8047:8047/udp
      - 8051:8051/udp
    environment:
      - JUICEBOX_HOST=192.168.10.18
      - UPDATE_UDPC=true
      - JPP_HOST=192.168.10.10
      - ENELX_PORT=8051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./log:/log #Optional
```
